### ISSUE TITLE
pepc: error: CPU 0 does not support C-state prewake

### ISSUE THREAD

**Issue by siavashr** [intel/pepc#8]
after running
pepc cstates config --cstate-prewake on

I get the following error message:
pepc: warning: the 'tuned' service is active! It may override the changes made by 'pepc'.
Consider having 'tuned' disabled while experimenting with power management settings.
pepc: error: CPU 0 does not support C-state prewake

**Comment by dedekind** [comment]
@siavashr Hello,

You did not formulate the question or what is you think the issue. I'll try to guess.

1. You did not expect the error message. Well, it just means your CPU does not support the pre-wake feature. This feature is supported by server CPUs, I am not aware of client CPUs that support it, but I may be mistaken. What is your CPU? You could check in /proc/cpuinfo.

2. The error message is not clear enough. I'd agree. I think it should also provide a list of CPU model numbers that do support the pre-wake feature. More details needed.

3. The warning is confusing. I agree. While 'tuned' does interfere with pepc, it does so only for some things, such as frequency limits and EPP value. It does not interfere with  C-state pre-wake feature. So the warning is not very useful in this case. Moreover, it makes no sense printing the warning because the feature is not supported anyway.

**Comment by dedekind** [comment]
Also the error message says "CPU 0 does not support", even though it is the case for all CPUs, not only CPU 0.

**Comment by dedekind** [comment]
@siavashr We've improved the error message. We also made sure the 'tuned' message is not printed in your case. But since your CPU just does not support the C-state prewake feature, there is not much more we can do.

Can I close this issue?

**Comment by dedekind** [comment]
Closing.
